#ifndef BUH_CORE_CONFIG_H
#define BUH_CORE_CONFIG_H

#define MAX_WEAPONS 32
#define MAX_ITEMS 128
#define MAX_ENEMIES 512
#define MAX_BULLETS 512
#define MAX_DROPS 256
#define MAX_WEAPON_SLOTS 6
#define MAX_WEAPON_LEVEL 4
#define MAX_SHOP_SLOTS 12
#define MAX_PUDDLES 64

#define WINDOW_W 1280
#define WINDOW_H 720
#define ARENA_W 4000
#define ARENA_H 4000
#define VIEW_W 1180
#define VIEW_H 640
#define ITEM_POPUP_DURATION 4.5f
#define SWORD_ORBIT_SPEED 2.4f
#define SWORD_ORBIT_RANGE_SCALE 1.25f
#define SWORD_ORBIT_WIDTH 22
#define SWORD_ORBIT_HIT_COOLDOWN 0.2f

#define MAX_LEVELUP_CHOICES 16
#define MAX_WEAPON_FX 16
#define MAX_CHARACTERS 16
#define MAX_SKILL_TREE_UPGRADES 64
#define MAX_SKILL_TREE_CUSTOM_NODES 64

#endif

